silverstripe/silverstripe-graphql

- README.md
- examples/_config/config.yml
- examples/code/GroupTypeCreator.php
- examples/code/MemberTypeCreator.php
- examples/code/ReadMembersQueryCreator.php
- src/DataObjectInterfaceTypeCreator.php
- src/FieldCreator.php
- src/Manager.php
- src/Pagination/Connection.php
- src/Pagination/PageInfoType.php
- src/Pagination/PaginatedQueryCreator.php
- src/Pagination/SortDirectionType.php
- src/Pagination/SortInputType.php
- src/QueryCreator.php
- src/TypeCreator.php
- tests/ConnectionTest.php
- tests/Fake/DataObjectFake.php
- tests/Fake/PaginatedQueryFake.php
- tests/Fake/TypeCreatorFake.php
- tests/Util/CaseInsensitiveFieldAccessorTest.php
> Pagination support

- README.md
- examples/code/CreateMemberMutationCreator.php
- examples/code/MemberTypeCreator.php
- examples/code/ReadMembersQueryCreator.php
> DOCS Implement canView checks into ReadMembersQueryCreator examples

- README.md
- examples/_config/config.yml
- examples/code/PaginatedReadMembersQueryCreator.php
- examples/code/ReadMembersQueryCreator.php
* Add GraphQL syntax highlighting to readme.
> DOCS Clearly differentiate readMembers and paginatedReadMembers queries

- src/Controller.php
related to https://github.com/silverstripe/silverstripe-framework/pull/6500, but really just sanitisation
> Fix remove 'url' from request data

- src/Controller.php
Required for https://github.com/silverstripe/silverstripe-framework/pull/6509
> API Change handling of non-ajax posted variables

- README.md
- _config/routes.yml
- src/Auth/AuthenticatorInterface.php
- src/Auth/BasicAuthAuthenticator.php
- src/Auth/Handler.php
- src/Auth/MemberAuthenticator.php
- src/Controller.php
- tests/Auth/HandlerTest.php
- tests/ControllerTest.php
- tests/Fake/BrutalAuthenticatorFake.php
- tests/Fake/PushoverAuthenticatorFake.php
> ENHANCEMENT Provide default authentication rules for /graphql path

- README.md
> DOCS Fix configuration example and update docs re: authenticators

- src/Auth/BasicAuthAuthenticator.php
> FIX Do not check Member context in BasicAuthAuthenticator

- tests/ScaffoldingTest.php
> Assertions about fixed_fields

- examples/_config/config.yml
- examples/code/Post.php
> Fix examples

- .travis.yml
- composer.json
See https://github.com/silverstripe/silverstripe-framework/issues/6705
> Drop PHP 5.5

- src/Controller.php
Requires https://github.com/silverstripe/silverstripe-framework/pull/6725
> Update versioned namespace

- examples/_config/config.yml
> FIX Update configuration namespace in example YAML

- phpunit.xml.dist
Prevents coverage of "examples" and "tests" folder, etc
> Update code coverage whitelist path

- .travis.yml
- README.md
- composer.json
- examples/code/CreateMemberMutationCreator.php
- examples/code/ReadMembersQueryCreator.php
- src/Manager.php
- src/Pagination/Connection.php
- src/Pagination/PageInfoTypeCreator.php
- src/Pagination/PaginatedQueryCreator.php
- src/Pagination/SortInputTypeCreator.php
- src/Scaffolding/Scaffolders/CRUD/Create.php
- src/Scaffolding/Scaffolders/CRUD/Delete.php
- src/Scaffolding/Scaffolders/CRUD/Read.php
- src/Scaffolding/Scaffolders/CRUD/Update.php
- src/Scaffolding/Scaffolders/DataObjectScaffolder.php
- src/Scaffolding/Scaffolders/MutationScaffolder.php
- src/Scaffolding/Scaffolders/QueryScaffolder.php
- src/Scaffolding/Scaffolders/UnionScaffolder.php
- tests/Fake/MutationCreatorFake.php
- tests/Fake/QueryCreatorFake.php
- tests/ManagerTest.php
- tests/Scaffolding/Scaffolders/CRUD/CreateTest.php
- tests/Scaffolding/Scaffolders/CRUD/DeleteTest.php
- tests/Scaffolding/Scaffolders/CRUD/ReadTest.php
- tests/Scaffolding/Scaffolders/CRUD/UpdateTest.php
- tests/Scaffolding/Scaffolders/DataObjectScaffolderTest.php
- tests/Scaffolding/Scaffolders/MutationScaffolderTest.php
- tests/Scaffolding/Scaffolders/QueryScaffolderTest.php
- tests/Scaffolding/Scaffolders/UnionScaffolderTest.php
This opens up the option to upgrade to `graph-php@0.8`
Fixes https://github.com/silverstripe/silverstripe-graphql/issues/47
Dependencies https://github.com/silverstripe/silverstripe-asset-admin/pull/474
> Fix types no longer return callbacks

- src/Auth/BasicAuthAuthenticator.php
- src/Auth/MemberAuthenticator.php
- src/Manager.php
- tests/ManagerTest.php
See https://github.com/silverstripe/silverstripe-framework/pull/6829 for parent PR
> Upgrade for authentication refactor

- tests/ControllerTest.php
Main issue: https://github.com/silverstripe/silverstripe-framework/issues/6681
See https://github.com/silverstripe/silverstripe-framework/pull/7037 for framework pull request
> Update for app object

- .upgrade.yml
- src/Controller.php
- src/DataObjectInterfaceTypeCreator.php
- tests/Scaffolding/Scaffolders/OperationScaffolderTest.php
- tests/Scaffolding/Util/TypeParserTest.php
Part of https://github.com/silverstripe/silverstripe-framework/issues/7104
> Fix upgrader deltas

- src/Scaffolding/Scaffolders/CRUD/Create.php
so data is the same as if queried again
> Fix query the object after creation

- src/Scaffolding/Scaffolders/CRUD/Read.php
- src/Scaffolding/Scaffolders/QueryScaffolder.php
- tests/Scaffolding/Scaffolders/CRUD/ReadTest.php
- tests/Scaffolding/Scaffolders/QueryScaffolderTest.php
Otherwise you only get a list of fields all with null values
> Fix list scaffolded DataObjects when not paginated

- README.md
- examples/code/MemberTypeCreator.php
- examples/code/PaginatedReadMembersQueryCreator.php
Oversight from https://github.com/silverstripe/silverstripe-graphql/issues/47
> Fixed type use in examples

- src/Manager.php
GraphiQL expects objects to have fields, and if these aren't defined, they're just empty arrays and graphiql throws on that validation exception. While it's an edge case and probably more of a bug with the third party tool, I can't see a very good reason why we would want to have these empty roots anyway.
> MINOR: Don't add roots to the schema if they're empty

- src/Scaffolding/Scaffolders/QueryScaffolder.php
- tests/Scaffolding/Scaffolders/QueryScaffolderTest.php
- can set default limit with limit or defaultLimit
- can set maximum limit with maximumLimit
I am unsure what kind of error to throw when limit is set but pagination is false.
Resolves #115
> pagination limits can now be set by scaffolding

- .travis.yml
- src/Scaffolding/Scaffolders/CRUD/Update.php
- tests/Scaffolding/Scaffolders/CRUD/UpdateTest.php
Resolves https://github.com/silverstripe/silverstripe-graphql/issues/105
> Remove ID from Update, add to Input

- src/Manager.php
- src/Scaffolding/Scaffolders/CRUD/Create.php
- src/Scaffolding/Scaffolders/CRUD/Delete.php
- src/Scaffolding/Scaffolders/CRUD/Read.php
- src/Scaffolding/Scaffolders/CRUD/ReadOne.php
- src/Scaffolding/Scaffolders/CRUD/Update.php
- src/Scaffolding/Scaffolders/ListQueryScaffolder.php
- src/Scaffolding/Scaffolders/MutationScaffolder.php
- src/Scaffolding/Scaffolders/OperationScaffolder.php
- src/Scaffolding/Scaffolders/PaginationScaffolder.php
- src/Scaffolding/Scaffolders/QueryScaffolder.php
- src/Scaffolding/Scaffolders/SchemaScaffolder.php
- src/Scaffolding/Scaffolders/UnionScaffolder.php
- tests/Scaffolding/Scaffolders/CRUD/CreateTest.php
- tests/Scaffolding/Scaffolders/CRUD/DeleteTest.php
- tests/Scaffolding/Scaffolders/CRUD/ReadOneTest.php
- tests/Scaffolding/Scaffolders/CRUD/ReadTest.php
- tests/Scaffolding/Scaffolders/CRUD/UpdateTest.php
- tests/Scaffolding/Scaffolders/ItemQueryScaffolderTest.php
- tests/Scaffolding/Scaffolders/SchemaScaffolderTest.php
Fixes #137
After this is merged, you can merge https://github.com/silverstripe/silverstripe-versioned/pull/111
> BUG Fix broken createArgs() for scaffolded reads

- README.md
Per https://github.com/silverstripe/silverstripe-graphql/issues/140#issuecomment-365414008
> MINOR: Add pagination to query example

- .travis.yml
Parent issue https://github.com/silverstripeltd/open-sourcerers/issues/31
> Target SS4.3.x-dev in travis.

- src/Scaffolding/Scaffolders/ArgumentScaffolder.php
- src/Scaffolding/Scaffolders/OperationScaffolder.php
- src/Scaffolding/Util/StringTypeParser.php
- tests/Scaffolding/Scaffolders/ArgumentScaffolderTest.php
- tests/Scaffolding/Scaffolders/OperationScaffolderTest.php
- tests/Scaffolding/Util/StringTypeParserTest.php
Resolves https://github.com/silverstripe/silverstripe-graphql/issues/153
> ENHANCEMENT: Allow non-internal input types passed as args

- src/Scaffolding/Scaffolders/ListQueryScaffolder.php
Issue: https://github.com/tractorcow-farm/silverstripe-fluent/issues/414
Required for new unit tests for https://github.com/silverstripe/silverstripe-versioned/pull/182
> NEW Add getSortableFields to return sortable fields for query

- README.md
See https://github.com/silverstripe/silverstripe-graphql/pull/166
> Middleware docs

- README.md
Update a few things where information was incorrect or missing
> Minor changes to documentation

- src/Pagination/Connection.php
> BUG Ensure queries are sorted before limiting

- README.md
- src/Controller.php
- tests/ControllerTest.php
Added "Allow-Credentials" in static $cors and addCorsHeaders() to allow modification in yaml. 
This is to fix issue when accepting request from other ip address that has "withCredentials" set to true.
> Added "Allow-Credentials" in static $cors and addCorsHeaders()

- src/Scaffolding/Scaffolders/CRUD/Read.php
This patch also fixes the cms page history panel and silverstripe/installer tests
> CRUD/Read to beware of QueryFilterAware

- src/Extensions/IntrospectionProvider.php
I’m only really opening this because I keep getting bugged by exceptions logged in Sentry 😅. Unauthenticated requests to `admin/graphql/types` currently trigger a server error (an exception bubbles up from `getManager()`->`applyManagerContext()`->`getRequestUser()`), this changes it to instead return:
```json
{"errors":[{"message":"Authentication required"}]}
```
This is the same approach as the main query handling: https://github.com/silverstripe/silverstripe-graphql/blob/3.1.0-rc1/src/Controller.php#L99-L120.
> FIX: 'types' endpoint should catch exceptions

- README.md
Updating the read me `Setting up a new GraphQL schema` link in the table of contents.
> Minor: Fix read me documentation link

- README.md
Added scope for disabling CSRF Middleware
> Disable CSRF example

- composer.json
Follows https://github.com/silverstripe/silverstripe-framework/issues/9344
> RFC-9344 Remove branch aliases

- .travis.yml
- composer.json
Follow up to https://github.com/silverstripe/silverstripe-graphql/pull/250
> Merge up asset-admin test into 3 branch

- src/Controller.php
> Add dummy request

- .travis.yml
- src/Scaffolding/StaticSchema.php
- tests/Scaffolding/StaticSchemaTest.php
See: https://github.com/dnadesign/silverstripe-elemental/issues/751
> ENHANCEMENT: Boot typenames outside graphql request

- README.md
- src/QueryFilter/DataObjectQueryFilter.php
- tests/QueryFilter/DataObjectQueryFilterTest.php
Fixes an error where fields of relations could not be filtered against.
Resolves 1) and 3) in #265
> FIX: correctly resolve field names of relations

- src/Schema/DataObject/FieldReconciler.php
- src/Schema/Type/ModelType.php
Resolves https://github.com/silverstripe/silverstripe-graphql/issues/322
Docs: https://github.com/silverstripe/silverstripe-framework/pull/9870
> MINOR: Remove exclude directive from mutation input types

- .travis.yml
Issue https://github.com/silverstripe/silverstripe-graphql/issues/382
> MNT Require recipe 4.x-dev, bump frameworktest

- src/Auth/Handler.php
> ENH Remove basic-auth

- src/Permission/PermissionCheckerAware.php
- tests/Permission/PermissionCheckerAwareTest.php
> [CVE-2021-28661] Add a CanViewPermissionChecker if permission checker is null

- src/Dev/Build.php
- src/Extensions/TestSessionEnvironmentExtension.php
- src/Schema/Logger.php
- src/Schema/Schema.php
- src/Schema/Storage/CodeGenerationStore.php
Resolves https://github.com/silverstripe/silverstripe-graphql/issues/389
Future -- add more logging throughout the entire build process for operations at the `DEBUG` level.
> NEW: Schema logger, set verbosity

- src/Schema/Schema.php
- src/Schema/Type/TypeReference.php
- tests/Schema/Type/TypeReferenceTest.php
Resolves https://github.com/silverstripe/silverstripe-graphql/issues/373
> NEW: Allow typeAsModel to be wrapped

- src/Schema/Schema.php
- src/Schema/SchemaBuilder.php
- tests/Schema/SchemaBuilderTest.php
Resolves https://github.com/silverstripe/silverstripe-graphql/issues/370
> NEW: src must be array

- .travis.yml
Travis failure "correctly" matches https://app.travis-ci.com/github/silverstripe/silverstripe-elemental/jobs/556073834
> MNT Add elemental behat test

- composer.json
- src/Scaffolding/Util/StringTypeParser.php
- tests/ConnectionTest.php
- tests/Fake/FakeResolveInfo.php
- tests/QueryFilter/ReadTest.php
- tests/Scaffolding/Scaffolders/CRUD/CreateTest.php
- tests/Scaffolding/Scaffolders/CRUD/DeleteTest.php
- tests/Scaffolding/Scaffolders/CRUD/ReadOneTest.php
- tests/Scaffolding/Scaffolders/CRUD/ReadTest.php
- tests/Scaffolding/Scaffolders/CRUD/UpdateTest.php
- tests/Scaffolding/Scaffolders/DataObjectScaffolderTest.php
- tests/Scaffolding/Scaffolders/ItemQueryScaffolderTest.php
- tests/Scaffolding/Scaffolders/ListQueryScaffolderTest.php
- tests/Scaffolding/Scaffolders/UnionScaffolderTest.php
Issue https://github.com/silverstripe/silverstripe-framework/issues/10250
> DEP Upgrade webonyx/graphql-php to v14

- src/Dev/DevelopmentAdmin.php
- src/Schema/Logger.php
You can't really override verbosity right now because it's explicitly set in DevelopmentAdmin
- Fixes https://github.com/silverstripeltd/product-issues/issues/519
> FIX Change Logger default verbosity to info

- .travis.yml
Issue https://github.com/silverstripe/silverstripe-framework/issues/10294
> MNT Do not allow failures on php 8.1

- .travis.yml
- src/Schema/BulkLoader/ExtensionLoader.php
Issue https://github.com/silverstripe/silverstripe-framework/issues/10294
> ENH PHP 8.1 compatibility fix
