src/Pagination/Connection.php, tests/ConnectionTest.php
Mainly designed to bridge case sensitivity between GraphQL (defaults to lower camel) and the SS ORM (defaults to upper camel). Will also come in handy for custom in-memory sorts, e.g. File.size
/cc @wilr
=> Allow sort field mapping

README.md, src/Pagination/Connection.php, src/Pagination/SortDirectionType.php, src/Pagination/SortInputType.php
`sortBy` now only accepts the whitelisted field names. Marking as an API change since queries will need to change from quoted to unquoted strings.
=> API: Whitelist sortBy field using an EnumType

README.md, src/Controller.php, src/DataObjectInterfaceTypeCreator.php, src/FieldCreator.php, src/GraphiQLController.php, src/InterfaceTypeCreator.php, src/Manager.php, src/MutationCreator.php, src/OperationResolver.php, src/Pagination/Connection.php, src/Pagination/PageInfoType.php, src/Pagination/PaginatedQueryCreator.php, src/Pagination/SortDirectionType.php, src/Pagination/SortInputType.php, src/TypeCreator.php, src/Util/CaseInsensitiveFieldAccessor.php, tests/FieldCreatorTest.php
API PaginatedQueryCreator is abstract
PSR2 cleanup
PHPDoc cleanup
=> API Standardise OperationResolver::resolve()

src/Util/CaseInsensitiveFieldAccessor.php
=> Improve CaseInsensitiveFieldAccessor

_config/routes.yml, src/Controller.php
Does not fix, but is related to https://github.com/silverstripe/silverstripe-graphql/issues/30.
A better solution is to allow stage to be configurable per request, but at least this sets a good default reading stage.
=> API Apply draft to default graphql route

src/Manager.php
More decoupled than relying on Member::currentUser() directly in canView()
=> Pass currentUser through context

src/Pagination/Connection.php, tests/ConnectionTest.php
Args can reference input types, which in turn need a reference in the $manager instance,
same as setConnectionType().
=> Connection->setArgs() callable support

README.md
Prevents fatal error (PHP 7.1) of an incompatible method declaration when running the example in graphiql.
Removed MyDataObject from ReadmembersQueryCreator as it was not used.
=> DOC Add ResolveInfo type hint to resolve() example

README.md, examples/_config/config.yml, src/Auth/AuthenticatorInterface.php, src/Auth/BasicAuthAuthenticator.php, src/Auth/Handler.php, src/Controller.php, src/Manager.php, tests/Auth/HandlerTest.php, tests/ControllerTest.php, tests/Fake/BrutalAuthenticatorFake.php, tests/Fake/PushoverAuthenticatorFake.php, tests/ManagerTest.php
The BasicAuth implementation will adequately protect the API endpoint, and will validate against a Member, but (by design) it will not be stored in the session and as such cannot be used for native SilverStripe permission checking (`Page::canView`).
This change adds an `AuthenticatorInterface` which can be implemented by various authenticator classes to use the `HTTPRequest` provided to GraphQL to authenticate against members, and return a `Member` instance if successful.
This PR includes a `BasicAuthAuthenticator`.
Example configuration:
```yaml
SilverStripe\GraphQL:
authenticators:
- class: SilverStripe\GraphQL\Auth\BasicAuthAuthenticator
priority: 10
```
The only non-obvious implication here is that even if you have a global basic auth requirement set on your site, you'll still need to …
=> API Add support for BasicAuth to be used for native permission checks

src/Util/CaseInsensitiveFieldAccessor.php
This caused issues with multiple setName() invocations
on Folder: The setter modifies the value. If the setter is then called
again with the same value, it falsifies the results.
=> Only call setters once on CaseInsensitiveFieldAccessor

composer.json
We'll want to keep 0.1 for a non-stable release line
which is compatible with SilverStripe 3.x.
The backport to 3.x hasn't been started yet,
but we don't want to create separate 1.x and 2.x
release lines just yet since it'll communicate
API stability according to semantic versioning.
Once the 0.1 branch for 3.x goes stable,
we might have a 1.0 release for 3.x,
and a 2.0 release for 4.x compat.
=> Use 0.2 branch alias

src/Auth/Handler.php
Priority (in its current implementation) is ordered from highest to lowest in order of which authenticators are checked.
`MemberAuthenticator` should be the last class to be checked as it is the fallback authentication option.
Contributes to #60
=> FIX Member handler should be checked last

src/Controller.php
When submitting a query to GraphQL via a POST message, in the case where the 'variables' entity is non-null, an extra call to json_decode is made which is unnecessary and causes a PHP error because the entity is already decoded earlier in the block.
=> POST queries with variables entity causes error

README.md, _config/config.yml, src/Controller.php, tests/ControllerTest.php
Added code to index() to detect a CORS preflight OPTIONS request.
Added getCorsResponse() to append the correct headers for a CORS request. 
Also checks the origin is an allowed domain for cross-origin requests. 
Included unittests for invalid origin, valid origin, OPTIONS request type.
=> API Added CORS pre-flight handler (fixes #66)

_config/config.yml, src/Controller.php, src/Scaffolding/Scaffolders/DataObjectScaffolder.php, tests/ControllerTest.php
Update for https://github.com/silverstripe/silverstripe-framework/pull/6641
=> API Update graphql to use new config

composer.json, tests/ConnectionTest.php, tests/Fake/DataObjectFake.php, tests/Fake/FakeRedirectorPage.php, tests/Fake/FakeResolver.php, tests/Fake/FakeSiteTree.php, tests/Fake/MutationCreatorFake.php, tests/Fake/OperationScaffolderFake.php, tests/Fake/PaginatedQueryFake.php, tests/Fake/QueryCreatorFake.php, tests/Fake/TypeCreatorFake.php, tests/FieldCreatorTest.php, tests/TypeCreatorTest.php, tests/Util/CaseInsensitiveFieldAccessorTest.php
This pull request:
* implements a dev autoloader
* fixes inconsistent namespaces in test classes
* implements `SilverStripe\Dev\TestOnly` in test stubs
* fixes some PSR-2 compat in stubs
* rearranges some class imports a bit so they're alphabetically ordered
=> FIX Correct namespaces in test classes, add PSR-4 autoloader, sort some class imports

src/Auth/BasicAuthAuthenticator.php, src/Auth/Handler.php, tests/Auth/HandlerTest.php, tests/ControllerTest.php, tests/Fake/FalsyAuthenticatorFake.php
AuthenticatorInterface specifies that a ValidationException will be thrown on
authentication failure, yet BasicAuthAuthenticator and stub test classes are
set to return null. Adjusted to match interface.
---
Note: I'm treating this as a fix as it's an incompatibility against the existing
interface API.
Resolves #60
Example client update to suit is in this PR as well as sminnee/silverstripe-apikey#9
=> FIX Allow Authenticator exceptions to be returned to client

src/Controller.php, tests/ControllerTest.php
Currently, a wildcard as `Allow-Origin` seems to be ignored. This PR fixes this.
=> Allow wildcard in allowed-origin CORS settings.

src/Controller.php
GraphiQL passes variables as empty string and `GraphQL\Validator\Rules\QueryComplexity::setRawVariableValues()` chokes on a non-array value.
=> Force $variables to cast as array

.travis.yml, composer.json, phpunit.xml.dist
See https://github.com/silverstripe/silverstripe-framework/issues/7405
Merge after https://github.com/silverstripe/silverstripe-framework/pull/7395
Blocked by https://github.com/silverstripe/silverstripe-graphql/pull/122
Tested file listing in CMS.
Test (after merging the framework pull request):
```
composer config repositories.graphql vcs https://github.com/open-sausages/silverstripe-graphql.git
composer require "silverstripe/graphql:dev-pulls/vendorise-me-baby as 0.2.x-dev"
```
=> Expose as vendor module

src/Scaffolding/Scaffolders/ArgumentScaffolder.php, tests/Scaffolding/Scaffolders/ArgumentScaffolderTest.php
Graphiql coerces `null` into a string `"null"`. It shouldn't be in the schema in the first place if it's null.
=> BUGFIX: Prevent defaultValue from being added to args when null

_config/config.yml, src/Controller.php, src/Manager.php, src/Scaffolding/Scaffolders/DataObjectScaffolder.php, src/Scaffolding/Scaffolders/OperationScaffolder.php, src/Scaffolding/Scaffolders/QueryScaffolder.php, src/Scaffolding/Scaffolders/SchemaScaffolder.php, src/Scaffolding/Util/ArrayTypeParser.php, src/Scaffolding/Util/OperationList.php, src/Scaffolding/Util/StringTypeParser.php, tests/ControllerTest.php, tests/Scaffolding/Scaffolders/DataObjectScaffolderTest.php, tests/Scaffolding/Scaffolders/OperationScaffolderTest.php, tests/Scaffolding/Scaffolders/QueryScaffolderTest.php, tests/Scaffolding/Scaffolders/SchemaScaffolderTest.php, tests/Scaffolding/Util/ArrayTypeParserTest.php, tests/Scaffolding/Util/OperationListTest.php, tests/Scaffolding/Util/StringTypeParserTest.php
BUG Prevent un-extendable config by shifting defaults into PHP
BUG Remove dependency on Doctrine module breaking with --prefer-dist
BUG Fix tests not checking cors port
ENHANCEMENT Clean up Controller::index() method and make lovely
ENHANCEMENT Optimise all imports
Fixes #118
=> BUG Fix cors breaking if referer header is present

README.md, src/Scaffolding/Scaffolders/SchemaScaffolder.php
The context key is `currentUser`, so updated the examples to reflect this. Also the indentation level for `resolver` is important, and I've made the DataObjectScaffolder instantiation go through injector.
=> FIX DataObjectScaffolder is now injectable, and typos in readme are fixed

src/Manager.php
Currently the interface doesn't mention a return value on the method `provideGraphQLScaffolding`. This is an issue when the method is actually called as the manager relies on the return value.
This PR removes that reliance (as it probably should be from the get go)
I've targeted 2.0 with this as a patch as the documented API doesn't mention a return value on the interface.
=> FIX Don't rely on return value of GraphQL scaffolding providers

src/Manager.php, src/Middleware/QueryMiddleware.php, tests/Middleware/DummyResponseMiddleware.php, tests/Middleware/QueryMiddlewareTest.php
See #164
Note: This is actually a new minor version (new features) so it should go into a `1` branch (which I haven't created yet), so don't actually merge this please. :)
Tests should come if we think this approach looks good.
I won't post the specifics, but I can confirm that specific queries correctly "spy" on the correct classes queried by the internal graphql.
Another todo is respect versioned deletions (won't affect LastEdited, but will appear as new _Versioned rows). This todo is marked in the code.
@unclecheese / @chillu  / @stevie-mayhew for review.
I've seen performance increases of up to 6x for cached results. ;)
=> ENHANCEMENT Proof of concept of cached graphql queries

src/Scaffolding/Scaffolders/DataObjectScaffolder.php
As titled. The object comes before the class to check against.
=> FIX Incorrect parameter order of is_subclass_of

README.md, _config/config.yml
```
PHP Deprecated: Not quoting the scalar "%$SilverStripe\GraphQL\Manager.admin" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0 on line 9. in /Users/robbieaverill/dev/ss43/vendor/symfony/yaml/Inline.php on line 357
PHP Deprecated: Not quoting the scalar "%$SilverStripe\GraphQL\Controller.admin" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0 on line 4. in /Users/robbieaverill/dev/ss43/vendor/symfony/yaml/Inline.php on line 357
PHP Deprecated: Not quoting the scalar "%$SilverStripe\GraphQL\Manager.default" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0 on line 14. in …
```
=> FIX Quote injector alias references, deprecated and removed support for in Symfony 4

src/Scaffolding/Traits/DataObjectTypeTrait.php
The `ReadVersions` ListQueryScaffolder implementation in silverstripe/versioned sets these properties, since they're private it'd be creating its own version of them. This leads to a fragile API surface.
We prefer not to use private visiblity in SilverStripe code, so this is increasing it to protected.
=> API Increase visibility of private properties, used by ReadVersions in silverstripe/versioned

src/Scaffolding/Scaffolders/QueryScaffolder.php, tests/Scaffolding/Scaffolders/QueryScaffolderTest.php
For the `3` branch fix:
* https://github.com/silverstripe/silverstripe-graphql/pull/182
* https://github.com/silverstripe/silverstripe-versioned/pull/176
=> Fix QueryScaffolder not using inheritance types

src/Scaffolding/Scaffolders/CRUD/Create.php, src/Scaffolding/Scaffolders/CRUD/Delete.php, src/Scaffolding/Scaffolders/CRUD/Read.php, src/Scaffolding/Scaffolders/CRUD/ReadOne.php, src/Scaffolding/Scaffolders/CRUD/Update.php, src/Scaffolding/Scaffolders/DataObjectScaffolder.php, src/Scaffolding/Scaffolders/ListQueryScaffolder.php, src/Scaffolding/Scaffolders/MutationScaffolder.php, src/Scaffolding/Scaffolders/QueryScaffolder.php, src/Scaffolding/Traits/DataObjectTypeTrait.php
Resolves: https://github.com/silverstripe/silverstripe-graphql/issues/176
=> NEW: Refactor OperationScaffolder subclasses to use resolved type name

src/Scaffolding/Scaffolders/CRUD/ReadOne.php
In most cases the canView permission was intended to be checked against the actual object from the database as the object state may have some play on whether the object is accessible by the user.
This was reported in an issue on silverstripe-elemental: https://github.com/dnadesign/silverstripe-elemental/issues/586 . I also have a "custom resolver" fix in that repo but I figure this is a common use case and it's a pretty quick win to get this fixed here.
=> FIX Check readOne permissions against resolved DataObject

src/Scaffolding/Scaffolders/CRUD/ReadOne.php
This restores the similar fallback behaviour before https://github.com/silverstripe/silverstripe-graphql/pull/207 was merged, but still gives priority to the specific item you are viewing if it exists
=> FIX Fall back to checking a singleton for canView() if no specific item exists

src/Manager.php
This prevents exceptions from being thrown for issues caused by invalid
user-input, preventing spam from being introduced to error monitors
such as Raygun.
This fixes #218
=> FIX: Return HTTP 400 for an incomplete query

src/Scaffolding/Scaffolders/CRUD/Create.php, src/Scaffolding/Scaffolders/CRUD/Delete.php, src/Scaffolding/Scaffolders/CRUD/Read.php, src/Scaffolding/Scaffolders/CRUD/ReadOne.php, src/Scaffolding/Scaffolders/CRUD/Update.php, src/Scaffolding/Scaffolders/DataObjectScaffolder.php, src/Scaffolding/Scaffolders/ListQueryScaffolder.php, src/Scaffolding/Scaffolders/MutationScaffolder.php, src/Scaffolding/Scaffolders/QueryScaffolder.php, src/Scaffolding/Traits/DataObjectTypeTrait.php
This introduced a number of regressions due to scaffolded queries no longer returning unions.
How we handle inheritance and unions has turned into a bigger discussion that will likely result in a more aggressive, lower-level change. https://github.com/silverstripe/silverstripe-graphql/issues/215
Given the short shelf life of both this change, or the bug that it was trying to fix, the best option here seems to be to revert this and aim to solve it properly.
=> Revert "NEW: Refactor OperationScaffolder subclasses to use resolved type name"

src/Manager.php
`graphql-devtools` chokes on it otherwise
=> BUGFIX: Allow mutations to be null. 

README.md, src/Scaffolding/Scaffolders/DataObjectScaffolder.php, src/Scaffolding/Scaffolders/OperationScaffolder.php, src/Scaffolding/Scaffolders/SchemaScaffolder.php, tests/Scaffolding/Scaffolders/DataObjectScaffolderTest.php, tests/Scaffolding/Scaffolders/SchemaScaffolderTest.php
When scaffolding Page with a read operation,
the default behaviour used to be the creation of readPage, readSiteTree, readRedirectorPage etc.
In fact, the readPage query is sufficient, since it returns a union of all these types. The rest is noise,
with the slight advantage that types at the end of an inheritance chain (without descendants)
get away without unions in the return type.
The default behaviour is a bit more useful on create and update operations,
since those require a specific input type - unions aren't allowed here.
So in order to fully create subclasses, you need createPage vs. createRedirectorPage.
I'm proposing that we make this well-documented opt-in behaviour,
with the admin/graphql schema opting in for each type on create and update.
I don't see a reason why anyone …
=> API Don't create "peripheral" operations by default

README.md
Removing duplicate `Strict HTTP Method Checking` content in the read me file, which appears twice in a row.
=> Minor: Removing duplicate read me content

_config/dev.yml, src/Controller.php, src/Dev/State/DisableTypeCacheState.php
This also adds test state to set that new configuration option to false during test runs.
With recipe-kitchen-sink just running configuration for a single test class takes me 8s on my local machine. The test doesn't touch GraphQL at all plus the configuration done by the GraphQL module is only revelant for e2e tests as it's generating a cache file for client side consumption (with Apollo).
=> NEW Added ability to disable type caching on flush

.travis.yml
The master branch is testing against CMS 5, which at some point introduced a minimum PHP requirement of 7.2. This PR updates the Travis config from 7.1, in order to (hopefully) get the tests green again.
=> Update Travis to Xenial, use PHP 7.2 / 7.3

_config/config.yml
fixing
> PHP Deprecated: Not quoting the scalar "%$SilverStripe\GraphQL\PersistedQuery\GuzzleHTTPClient" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0
=> fix deprecation in config

_config/filters.yml
The wrong filter was set for endswith and startswith
* https://github.com/silverstripe/silverstripe-graphql/issues/245
=> BUG Reference the correct filters for endswith and startswith

src/Manager.php, src/Scaffolding/Scaffolders/CRUD/Create.php, src/Scaffolding/Scaffolders/CRUD/Delete.php, src/Scaffolding/Scaffolders/CRUD/Update.php
* several new extension points added
* these extension points allow to execute some custom code related to handling of user actions
* no functional changes apart from following fix
* fixed an issue in `Scaffolding/Scaffolders/CRUD/Delete.php` where variable `$info` wasn't passed into a function callback which prevented an existing extension point from ever passing this data through
* these changes are required for https://github.com/silverstripe/silverstripe-versioned-snapshots/pull/25
=> Operation extension points

.travis.yml
This adds the asset-admin tests to the graphql module. Asset-admin is the primary module that relies on graphql, so this serves as a sort of integration test.
=> BUG Add asset-admin test to travis build

composer.json, tests/ManagerTest.php, tests/Middleware/CSRFMiddlewareTest.php, tests/Middleware/HTTPMethodMiddlewareTest.php, tests/Scaffolding/Scaffolders/CRUD/CreateTest.php, tests/Scaffolding/Scaffolders/CRUD/DeleteTest.php, tests/Scaffolding/Scaffolders/CRUD/UpdateTest.php, tests/Scaffolding/Scaffolders/DataObjectScaffolderTest.php, tests/Scaffolding/Scaffolders/InheritanceScaffolderTest.php, tests/Scaffolding/Scaffolders/ListQueryScaffolderTest.php, tests/Scaffolding/Scaffolders/OperationScaffolderTest.php, tests/Scaffolding/Scaffolders/SchemaScaffolderTest.php, tests/Scaffolding/StaticSchemaTest.php, tests/Scaffolding/Util/ArrayTypeParserTest.php, tests/Scaffolding/Util/OperationListTest.php, tests/Scaffolding/Util/StringTypeParserTest.php
`expectExceptionMessageRegExp` is being deprecated in favour of `expectExceptionMessageMatches`
=> Replace deprecated exception assertion

README.md, src/Controller.php, tests/ControllerTest.php
Now that we support multiple schemas, it doesn't make sense that the CORS settings should be global. This allows you to merge in custom settings per instance and is BC with the current static config.
```
SilverStripe\Core\Injector\Injector:
SilverStripe\GraphQL\Controller.myController:
properties:
corsConfig:
Enabled: false
```
=> NEW: Allow instance override of CORS config

src/Manager.php
Needed for snapshots, and seems like it could be useful in other contexts.
=> MINOR: add result to onAfterMiddlware hook

.travis.yml
The asset-admin behat test now requires frameworktest to work because of https://github.com/silverstripe/silverstripe-asset-admin/pull/1038
=> BUG Require frameworktest for behat test

src/FieldAccessorInterface.php, src/Manager.php, src/Pagination/Connection.php, src/Scaffolding/Scaffolders/CRUD/Create.php, src/Scaffolding/Scaffolders/CRUD/Delete.php, src/Scaffolding/Scaffolders/CRUD/Read.php, src/Scaffolding/Scaffolders/CRUD/ReadOne.php, src/Scaffolding/Scaffolders/CRUD/Update.php, src/Scaffolding/Scaffolders/DataObjectScaffolder.php, src/Scaffolding/StaticSchema.php, src/Util/CaseInsensitiveFieldAccessor.php, src/Util/NaiveFieldAccessor.php, tests/Fake/FakeFieldAccessor.php, tests/Scaffolding/Scaffolders/DataObjectScaffolderTest.php, tests/Scaffolding/StaticSchemaTest.php
Moved from: https://github.com/silverstripe/silverstripe-graphql/pull/310
We need backward compat for all the core modules, so they can run on either v3 or v4. It's very difficult to do this at run time because the graphql queries are bound to components at build time, so having two separate queries is both a technical challenge and also hard to maintain.
The easier solution is to allow the graphql 3 queries to look like graphql 4 queries, and the main issue there is case sensitivity.
This pull request allows the optional provision of a field formatter function and field accessor service to abstract this away. By default, you still get the naive implementation of DBField == GraphQL Field, but in admin, we'll want to take advantage of a lowerCamelCase transform.
Todo:
* Unit testing
* …
=> NEW: Field formatting API, forward compatibility

_config/plugins.yml, src/Schema/Plugin/AbstractNestedInputPlugin.php, src/Schema/Registry/PluginRegistry.php, src/Schema/Schema.php
This fixes a number of errors that could come up when doing multiple schema builds where plugin state was polluted by preceding schemas. Plugins are no longer singletons, and are instead instantiated each time they are used. State that should be persisted for the duration of the build should be in static members, namespaced by the current schema.
=> NEW: Stateless plugins, plugin registry as simple list

_config/config.yml, src/Controller.php, src/PersistedQuery/RequestIDProcessor.php, src/PersistedQuery/RequestProcessor.php
This is only an idea that I'd like to develop further but looking for a bit of feedback on approach.
the motivation comes from setting up https://github.com/apollographql/apollo-link-persisted-queries which seems to be a common client library to use for persisted queries. Currently, Controller.php expects any GET request with a persisted query ID to supply that as a query param named `id`. By default apollo-link-persisted-queries has a different structure (a param that looks like `&extensions={"persistedQuery":{"version":1,"sha256Hash":"e2d83966...`) 
so the thought is to move the extraction of the query ID (and probably fetching the query from ID too) into an Injectable class so that different implementations can more easily created/added. 
If this looks reasonable I can also move the …
=> PoC: Move persisted request processing to injectable class

src/Config/SchemaContext.php, src/Schema/Resolver/DefaultResolverStrategy.php
The current logic is:
"For each resolver class, try very specific methods, down to really generic methods. "
This means a class with a generic method defined that is first in the resolver list will beat out a class with a more specific method that happens to be lower in the list. The outer loop should be the decreasing specificity of methods, and the inner loop should be the classes.
=> ENHANCEMENT: Resolver strategy isn't logical

.travis.yml, src/Schema/DataObject/CreateCreator.php
Required parameters cannot follow optional parameters in PHP 8 and later.
=> FIX Make trailing parameter optional to resolve deprecation

src/Schema/Schema.php
It's not used anywhere, and is "false advertisement"
since there's a whole lot of instance state which it doesn't cover
(e.g. procedural addType() calls, anything in SchemaContext).
If there was a reason to keep it, we shouldn't return a potentially
huge string as a signature, but rather use a hash.
This would also avoid accidentally disclosing potentially
sensitive (serialised) data in cache keys etc.
=> Remove Schema->getSignature()

src/Schema/Storage/CodeGenerationStore.php
I get this when I go to /admin/pages on a site with elemental installed
[Emergency] Uncaught TypeError: Return value of SilverStripe\GraphQL\Schema\Storage\CodeGenerationStore::getTypeMapping() must be of the type array, boolean returned
The file it's trying to retrieve is /.graphql/admin/__type-mapping.php
The contents of the file is 
```
<?php 
return array (
'DNADesign\\Elemental\\Models\\BaseElement' => 'Block',
...
'SilverStripe\\CMS\\Model\\VirtualPage' => 'VirtualPage',
);
```
What's happening is that this line is being called more than once, and `require_once` will return a bool(true) for each subsequent call.
Instead we should just use `require` so that it always reads the file and assigns the read value to `$mapping`
=> FIX Use require instead of require_once for type mapping function

src/Schema/Schema.php
sprintf() will fail if passed an empty array i.e. `...[]`
This fix ensure we don't attempt to use sprintf() when this happens
=> FIX Handle case where params is empty

src/Schema/Schema.php
It's unclear whether `SchemaModelCreatorInterface`
should support model identifiers which aren't classes,
so I've refrained from using `class_exists()` directly here.
=> Schema warning when model can't be found

src/Schema/Services/NestedInputBuilder.php, tests/Schema/Services/NestedInputBuilderTest.php
This PR aims to fix a bug in the `NestedInputBuilder` where a cyclic graph prohibits the building of all necessary nested types on filter and sort input-types.
=> FIX: input building in cyclic graphs

src/Pagination/Connection.php
For in new GraphQL 4 compatible node/edges implementation
Resolves https://github.com/silverstripe/silverstripe-graphql/issues/376#issuecomment-834046271
=> BUGFIX: Ensure referential equality of two connection types

_config/config.yml, src/Extensions/TestSessionEnvironmentExtension.php
Issue https://github.com/silverstripe/silverstripe-campaign-admin/issues/192
Related issue https://github.com/silverstripe/silverstripe-asset-admin/issues/1186
The travis config on graphql 4 isn't actually running a behat test, so I also created a one off test with cut down travis file where behat is not an allowable failure: https://travis-ci.com/github/silverstripe/silverstripe-graphql/builds/225807605 - the code state for this test was https://github.com/silverstripe/silverstripe-graphql/pull/380/commits/76bbd3f11217f638af0e0c04ef7208bdd5f8085c.  
The assumption is that fixing the asset-admin behat test will also fix the campaign-admin test that is the parent issue of this pr
=> NEW Add TestSessionEnvironmentExtension to support behat tests

src/Schema/DataObject/FieldAccessor.php
The inverse of the `many_many` relation is currently missing as a field. This PR fixes this.
=> Add access to belongs_many_many relation

src/Scaffolding/Scaffolders/DataObjectScaffolder.php
This is a tricky one with a lot of approaches for a fix, but this is the only way that doesn't break any APIs.
`versioned-snapshot-admin` is broken because it queries for fields like `absoluteLink` and `version` on the origin record of all snapshots. Sometimes, these origins don't have those fields. The most common case is "SnapshotEvent", which is basically an arbitrary point in time -- "imported translations", e.g. , and these fields don't exist.
In < 3.5, this failed gracefully, because [the accessor](https://github.com/silverstripe/silverstripe-graphql/blob/3.4/src/Scaffolding/Scaffolders/DataObjectScaffolder.php#L672) was a simple `$obj->obj($fieldName)`. In 3.5, we've introduced the `FieldAccessor` service as a new layer of abstraction. The service we use (for graphql 4 compat) is …
=> BUGFIX: Replace graceful failure of field access on dataobjects

composer.json, phpunit.xml.dist, tests/Auth/HandlerTest.php, tests/ConnectionTest.php, tests/ControllerTest.php, tests/ManagerTest.php, tests/Middleware/CSRFMiddlewareTest.php, tests/Middleware/HTTPMethodMiddlewareTest.php, tests/Middleware/MiddlewareProcessTestBase.php, tests/PersistedQuery/HTTPProviderTest.php, tests/PersistedQuery/JSONStringProviderTest.php, tests/QueryFilter/ReadTest.php, tests/Scaffolding/Scaffolders/ArgumentScaffolderTest.php, tests/Scaffolding/Scaffolders/CRUD/CreateTest.php, tests/Scaffolding/Scaffolders/CRUD/DeleteTest.php, tests/Scaffolding/Scaffolders/CRUD/ReadOneTest.php, tests/Scaffolding/Scaffolders/CRUD/ReadTest.php, tests/Scaffolding/Scaffolders/CRUD/UpdateTest.php, tests/Scaffolding/Scaffolders/DataObjectScaffolderTest.php, tests/Scaffolding/Scaffolders/InheritanceScaffolderTest.php, tests/Scaffolding/Scaffolders/ListQueryScaffolderTest.php, tests/Scaffolding/Scaffolders/OperationScaffolderTest.php, tests/Scaffolding/Scaffolders/SchemaScaffolderTest.php, tests/Scaffolding/Scaffolders/UnionScaffolderTest.php, tests/Scaffolding/StaticSchemaTest.php, tests/Scaffolding/Util/ArrayTypeParserTest.php, tests/Scaffolding/Util/OperationListTest.php, tests/Scaffolding/Util/StringTypeParserTest.php, tests/TypeCreatorTest.php, tests/Util/CaseInsensitiveFieldAccessorTest.php
Issue https://github.com/silverstripe/silverstripe-framework/issues/10019
=> API phpunit9 support

.travis.yml, composer.json, phpunit.xml.dist, tests/Auth/HandlerTest.php, tests/Middleware/CSRFMiddlewareTest.php, tests/Middleware/MiddlewareProcessTestBase.php, tests/Schema/DataObject/FieldAccessorTest.php, tests/Schema/IntegrationTest.php, tests/Schema/SchemaTest.php
Issue: https://github.com/silverstripe/silverstripe-framework/issues/10019
=> API phpunit 9 support

src/Schema/DataObject/DataObjectModel.php, src/Schema/Field/Field.php, src/Schema/Field/ModelField.php
Avoids calling `accessField()` which in turn calls `DataObject->obj()`. It isn't directly interested in the actual return value, but rather the *type* of this return value. Due to the way the ORM and DataObject is built, we can't guarantee lazy evaluation of those return values. Some of them cause database queries. One example here is `Versioned->versions()`, which performs in-memory operations on a (lazy) `DataList` that turn it into a (concrete) `ArrayList`.
Performing database queries slows down schema generation, but more importantly the database might not be available when we build the schema as part of a deployment operation (rather than a dev or production environment). For example, when creating a deployment package on CircleCI which then gets transferred to the actual production …
=> API New $class arg for DataObjectModel->getModelTypeForField()

src/Schema/Services/SchemaTranscriber.php
This is consistent with public/_resources which is also auto-generated by the CMS.
It enables sysadmins to lock down write access to public/ during runtime, with this potentially granular exception.
And it makes it easier to discover which part of the system is responsible for writing these files.
The change is backwards compatible with existing file locations,
although we probably want to remove that before going stable:
https://github.com/silverstripe/silverstripe-graphql/issues/384
Relies on equivalent PR to silverstripe/admin at https://github.com/silverstripe/silverstripe-admin/pull/1222
The docs are already stating this new location so this was more of an oversight:
https://docs.silverstripe.org/en/4/developer_guides/graphql/getting_started/building_the_schema/#viewing-the-generated- …
=> Use public/_graphql/ subfolder

.travis.yml, src/Schema/DataObject/CreateCreator.php, src/Schema/DataObject/UpdateCreator.php, src/Schema/Plugin/AbstractQueryFilterPlugin.php, src/Schema/Schema.php, src/Schema/Services/NestedInputBuilder.php, src/Schema/Type/ModelType.php, tests/Fake/FakeProduct.php, tests/Schema/Services/NestedInputBuilderTest.php
Regression from the DBFieldTypes work. Resolves https://github.com/silverstripe/silverstripe-graphql/issues/405
=> BUGFIX: Allow Enum fields in input types

src/Dev/Build.php, src/Schema/Type/ModelType.php
Depends on: https://github.com/silverstripe/silverstripe-framework/pull/10016
When `--no-database` is used, e.g. `vendor/bin/sake dev/graphql/build --no-database`, throw a helpful exception explaining where the database use may be coming from.
=> NEW: Support --no-database build option

.gitignore, phpcs.xml.dist, src/Dev/Build.php, src/Schema/Storage/CodeGenerationStore.php, tests/Schema/IntegrationTest.php
* Change `.graphql/` to `.graphql-codegen/`
* Force `clear = 1` because the new dir will hose your build without that. Caching is unreliable anyway.
=> MINOR: change graphql codegen dir, force clear

_config/config.yml, _config/tests.yml, src/Dev/State/DebugSchemaState.php, src/Schema/Storage/AbstractTypeRegistry.php, src/Schema/Storage/CodeGenerationStore.php, src/Schema/Storage/HashNameObfuscator.php, src/Schema/Storage/HybridObfuscator.php, src/Schema/Storage/NaiveNameObfuscator.php, src/Schema/Storage/NameObfuscator.php, src/Schema/Storage/templates/enum.inc.php, src/Schema/Storage/templates/interface.inc.php, src/Schema/Storage/templates/scalar.inc.php, src/Schema/Storage/templates/type.inc.php, src/Schema/Storage/templates/union.inc.php, src/Schema/Type/Enum.php, tests/Schema/IntegrationTest.php, tests/Schema/TestStoreCreator.php
Resolves https://github.com/silverstripe/silverstripe-graphql/issues/369
=> NEW: Obfuscate filenames to prevent IDE search issues

src/Dev/Build.php
There's no use case for not clearing the cache when rebuilding the schema
=> BUG Always nuke cache when manually rebuilding schema

.travis.yml
Need ^0.4.3 to fix guzzle issue - https://app.travis-ci.com/github/silverstripe/silverstripe-graphql/jobs/563992053#L481
Not including frameworktest in composer.json because it's running behat tests in the asset-admin module, not on the graphql module
=> MNT Require a caret version of frameworktest

_config/dev.yml, src/Dev/DevelopmentAdmin.php
The link in /dev for Build was being overridden by the graphql link. Also, /dev/graphql wasn't going to the index of `SilverStripe\GraphQL\Dev\DevelopmentAdmin`.
=> FIX Don't override Build link in /dev

composer.json
[Travis builds are failing](https://app.travis-ci.com/github/silverstripe/silverstripe-graphql/builds/250144247) on composer dependency resolution - it looks like this is caused by the alias, which needs to be removed in any event.
I don't think this will actually fix the tests until it has been merged (and packagist therefore picks up on it) - it may even need to be merged up to master before it takes effect.
- https://github.com/silverstripeltd/product-issues/issues/542
=> MNT Remote master branch alias
